# Generated by Django 5.1.2 on 2024-11-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_Paciente', models.CharField(max_length=255)),
                ('nome_Responsavel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('cpf_responsavel', models.CharField(max_length=255)),
                ('data_Nascimento', models.DateField()),
                ('idade_Paciente', models.IntegerField()),
                ('endereco', models.CharField(max_length=255)),
                ('data_Registro', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('concluído', 'Concluído')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_Voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_Voluntario', models.CharField(max_length=255)),
                ('cpf_Voluntario', models.CharField(max_length=255)),
                ('data_Nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('data_Registro', models.DateTimeField(auto_now_add=True)),
                ('idade_Voluntario', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Registro', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.CharField(choices=[('Psicologia Comportamental', 'Psicologia Comportamental'), ('Psicomotricidade', 'Psicomotricidade'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Aplicadora em ABA', 'Aplicadora em ABA'), ('Estimulação Pedagógica', 'Estimulação Pedagógica')], default='Psicologia Comportamental', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('concluído', 'Concluído')], default='pendente', max_length=10)),
                ('id_Paciente_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Webisite.paciente')),
                ('id_Voluntario_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Webisite.voluntario')),
            ],
        ),
    ]
