# Generated by Django 5.1.2 on 2024-11-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('horario', models.TimeField()),
                ('motivo', models.CharField(max_length=500)),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webisite.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=255)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=11)),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webisite.voluntario')),
            ],
        ),
    ]
