# Generated by Django 5.1.2 on 2024-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nome',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
