# Generated by Django 5.1.2 on 2024-11-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='idade_Voluntario',
        ),
    ]
