# Generated by Django 5.1.2 on 2024-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0002_remove_voluntario_idade_voluntario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='cpf_Voluntario',
            field=models.CharField(max_length=11),
        ),
    ]
