# Generated by Django 5.1.2 on 2024-11-08 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0002_visita_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nome_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nome_responsavel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='voluntario',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='nome',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_Nascimento',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 2, 55, 39, 816606, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_Registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 8, 2, 56, 18, 910677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereço',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_Paciente',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='idade_Paciente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cpf_Voluntario',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_Nascimento',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 2, 57, 34, 929385, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_Registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 8, 2, 57, 42, 241248, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='endereço',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='id_Voluntario',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='idade_Voluntario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nome_Voluntario',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_Paciente',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_Responsavel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
