# Generated by Django 5.1.2 on 2024-11-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0005_alter_paciente_id_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
