# Generated by Django 5.1.2 on 2024-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0006_rename_endereço_paciente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
    ]
