# Generated by Django 5.1.2 on 2024-11-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0009_remove_paciente_voluntario_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_Voluntario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome_Voluntario', models.CharField(max_length=255)),
                ('cpf_Voluntario', models.CharField(max_length=255)),
                ('data_Nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('endereço', models.CharField(max_length=255)),
                ('data_Registro', models.DateTimeField(auto_now_add=True)),
                ('idade_Voluntario', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
            ],
        ),
    ]
