# Generated by Django 5.1.2 on 2024-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0012_midiaeventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midiaeventos',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
