# Generated by Django 5.1.2 on 2024-11-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webisite', '0013_alter_midiaeventos_fotos'),
        ('Webisite', '0014_midiaeventos_delete_eventos'),
    ]

    operations = [
    ]
